# Generated by Django 5.1.6 on 2025-02-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_customuser_followers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post_images',
            new_name='PostImages',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='location',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
