# Generated by Django 5.1.6 on 2025-02-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_post_images_postimages_remove_post_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.DeleteModel(
            name='PostImages',
        ),
    ]
